### PR TITLE
little cleanup

### PR DESCRIPTION
**Pull request by fmccl**
- format
- allow palettedstorage to use NbtLittleEndianNetwork, will be used in chunk packets
- remove printlns
- ignore levelname.txt

### CODE REVIEW

**Comment by Adrian8115** [comment]
I would recommend that you switch to using the bedrock core crate instead of byte_order for reading/writing nums

**Comment by fmccl** [comment]
I don't think LE::read() should return LE<i32> I feel that it's duplicated information. For writing it makes more sense because you don't have to deal with the LE wrapper twice, you just put it in and forget about it

I'm working on switching it over to bedrock_core now, but the LE and BE thing also doesn't make sense for u8 and i8s so I'm gonna stick to byte order for that

**Comment by fmccl** [comment]
This ready to merge?

**Comment by Adrian8115** [comment]
seems good!

**Pull request merged**
