### PR TITLE
Load and save world player data

### PR DESCRIPTION
**Pull request by fmccl**

### CODE REVIEW

**Comment by fmccl** [comment]
```rs
use bedrock_rs::world::World;
use bedrock_rs::nbt::NbtTag;

fn main() {
    
    let mut world = World::open("test".into()).unwrap();

    let uuid = uuid::uuid!("dbbe106f-42d1-4cb9-8449-46239cf6199d");

    world.set_player(uuid, "abc".into(), NbtTag::String("defg".into())).unwrap().unwrap();

    println!("{:?}", world.get_player(uuid).unwrap().unwrap().unwrap());

}
```

**Comment by Adrian8115** [comment]
do you think it is a good idea to make people use 3x unwrap in `world.get_player(uuid).unwrap().unwrap().unwrap()`?

**Comment by fmccl** [comment]
I'll do that today yeah

note to self: empty root tags

**Comment by Adrian8115** [comment]
maybe add some comments about what certain functions do, but else lgtm!

**Comment by fmccl** [comment]
done it

**Comment by Adrian8115** [comment]
LGTM!

**Pull request merged**
